# BACnet Interoperability Scenario
# Professional BACnet/IP integration testing with realistic data center parameters

# Enable BACnet/IP interface for testing
bacnet:
  enabled: true                     # Enable BACnet/IP for integration testing
  device:
    objectName: "DC-BAS-TestSim"     # Unique device name for test environment
    objectIdentifier: 1001           # Test device instance (avoid conflicts)
    vendorIdentifier: 15             # Standard vendor ID for open source
    maxApduLengthAccepted: 1024      # Standard APDU length
    segmentationSupported: "segmented-both"
    modelName: "DC-BAS-TestSim"      # Test model identifier
    firmwareRevision: "1.0.0"
    applicationSoftwareVersion: "1.0.0"
  network:
    bind: "0.0.0.0"                 # Bind to all interfaces for testing
    port: 47808                      # Standard BACnet/IP port
    foreignDeviceTtl: 300            # Standard TTL for foreign device registration
  points:
    # Analog Inputs - Real-time sensor data
    zone_temp_ai: 100                # Zone temperature (°C)
    crac1_cooling_ai: 101            # CRAC-01 cooling output (kW)
    crac2_cooling_ai: 102            # CRAC-02 cooling output (kW) 
    crac3_cooling_ai: 103            # CRAC-03 cooling output (kW)
    it_load_ai: 104                  # IT equipment load (kW)
    
    # Analog Values - Setpoints and parameters
    zone_temp_setpoint_av: 200       # Temperature setpoint (°C)
    
    # Analog Outputs - Control commands
    crac1_cmd_ao: 300                # CRAC-01 capacity command (%)
    crac2_cmd_ao: 301                # CRAC-02 capacity command (%)
    crac3_cmd_ao: 302                # CRAC-03 capacity command (%)
    
    # Binary Inputs - Status feedback
    crac1_status_bi: 400             # CRAC-01 running status
    crac2_status_bi: 401             # CRAC-02 running status
    crac3_status_bi: 402             # CRAC-03 running status
    
    # Binary Outputs - Alarms and status
    system_alarm_bo: 500             # System alarm status

# Override simulation parameters for BACnet testing
simulation:
  duration_minutes: 30.0             # Shorter duration for integration testing
  timestep_s: 1.0                    # High resolution for protocol testing
  output_interval_s: 30.0            # Frequent data output for monitoring
  setpoint_c: 22.0                   # Standard data center setpoint

# Moderate load scenario for realistic BACnet data
room:
  initial_temp_c: 22.0               # Start at setpoint
  it_load_kw: 25.0                   # Reduced IT load for demo stability
  thermal_mass_kj_per_c: 2500.0      # Standard thermal mass

# Tuned PID for stable BACnet data streams
pid_controller:
  kp: 15.0                          # Increased for better response
  ki: 0.5                           # Increased integral gain for steady-state
  kd: 0.1                           # Light derivative action
  rate_limit: 50.0                  # Increased for faster demo response

# CRAC units optimized for demo responsiveness
crac_units:
  - unit_id: "CRAC-01"
    startup_time_s: 1.0             # Fast startup for demos
    shutdown_time_s: 1.0            # Fast shutdown for demos
  - unit_id: "CRAC-02"
    startup_time_s: 1.0             # Fast startup for demos
    shutdown_time_s: 1.0            # Fast shutdown for demos
  - unit_id: "CRAC-03"
    startup_time_s: 1.0             # Fast startup for demos
    shutdown_time_s: 1.0            # Fast shutdown for demos

# CRAC staging optimized for BACnet demonstration
staging_config:
  temp_error_threshold: 0.6         # Moderate staging threshold
  staging_delay_s: 120.0            # 2-minute staging delay
  destaging_delay_s: 240.0          # 4-minute destaging delay
  enable_rotation: true             # Enable rotation for demonstration

# Expected behavior for BACnet integration testing
expected_behavior:
  steady_state_time_s: 180.0        # Should stabilize within 3 minutes
  max_temp_error_c: 0.8             # Allow slightly looser control for stability
  bacnet_points_available: true     # All BACnet points should be readable
  bacnet_commands_responsive: true  # Commands should be accepted
  data_consistency: true            # Data should be consistent across points
  description: "BACnet/IP integration test with moderate load and stable control"

# Validation criteria for BACnet interoperability
validation_criteria:
  max_temperature_c: 23.0           # Allow for transient overshoot
  min_temperature_c: 21.0           # Allow for transient undershoot
  max_avg_error_c: 0.5              # Average error within 0.5°C
  max_std_dev_c: 0.4                # Standard deviation within 0.4°C
  min_control_accuracy_pct: 85.0    # 85% of time within ±0.5°C
  alarm_tolerance: ["transient"]    # Allow transient alarms during startup

# BACnet integration test points
bacnet_test_criteria:
  device_discovery: true            # Device should be discoverable
  point_readability: true           # All points should be readable
  command_acceptance: true          # Commands should be accepted
  data_update_rate_s: 30.0          # Data should update at least every 30s
  alarm_propagation: true           # Alarms should propagate to BACnet
  trending_capability: true         # Points should support trend logging