# CRAC Failure Scenario  
# Tests automatic failover and role promotion under equipment failure

# Override base simulation parameters
simulation:
  duration_minutes: 12.0
  setpoint_c: 22.0

# Room configuration overrides
room:
  initial_temp_c: 22.0
  it_load_kw: 50.0  # Higher load to stress system during failure

# Failure event definitions
failure_events:
  - type: "crac_failure"
    target_unit: "LEAD"
    failure_time_s: 300.0      # Failure at 5 minutes
    duration_hours: 1.0        # 1 hour failure duration
    description: "Force LEAD CRAC failure at t=5min for 1 hour"

# Expected system behavior under failure
expected_behavior:
  role_promotion_time_s: 15.0    # LAG should promote within 15s
  max_temp_rise_c: 1.0           # Max temperature excursion
  no_high_temp_alarm: true       # Should handle failure gracefully
  backup_unit_active: true       # Standby should activate
  description: "LAG should be promoted to LEAD role within 15s of failure"

# Validation criteria for emergency response
validation_criteria:
  max_temperature_c: 24.0
  max_promotion_time_s: 30.0        # Role promotion within 30s
  min_backup_capacity_pct: 80.0     # Minimum backup capacity
  alarm_tolerance: ["CRAC_FAIL"]    # Expected alarms
  required_alarms: ["CRAC_FAIL"]    # Must generate failure alarm