# Rising IT Load Scenario
# Tests LAG staging behavior under increasing thermal load

# Override base simulation parameters
simulation:
  duration_minutes: 15.0
  setpoint_c: 22.0

# Room configuration overrides
room:
  initial_temp_c: 22.0
  it_load_kw: 35.0  # Starting load (will ramp up)

# Load profile definition
load_profile:
  type: "ramp"
  start_time_s: 120.0        # Start ramp at 2 minutes
  end_time_s: 720.0          # End ramp at 12 minutes  
  start_load_kw: 35.0        # Initial load
  end_load_kw: 70.0          # Final load
  description: "Linear ramp from 35kW to 70kW over 10 minutes starting at t=2min"

# Expected system behavior
expected_behavior:
  lag_staging_time_s: 300.0
  max_temp_error_c: 2.0
  no_high_temp_alarm: true
  lag_staged_by_end: true
  description: "LAG unit should stage within 5 minutes, no HIGH_TEMP alarm should occur"

# Validation criteria for pass/fail
validation_criteria:
  max_temperature_c: 24.0
  max_sustained_error_c: 1.5
  min_lag_staging_time_s: 180.0    # Minimum 3 minutes before staging
  max_lag_staging_time_s: 420.0    # Maximum 7 minutes for staging
  alarm_tolerance: ["SENSOR_STUCK"]