# Baseline Scenario
# Standard operating conditions for system validation

# Override base simulation parameters  
simulation:
  duration_minutes: 60.0
  setpoint_c: 22.0
  
# Standard room conditions - Performance optimized
room:
  initial_temp_c: 22.0
  it_load_kw: 35.0  # Optimized load matching default config

# Expected steady-state behavior - Documentation claims
expected_behavior:
  steady_state_time_s: 300.0     # Should reach steady state in 5 minutes
  max_temp_error_c: 0.5          # Tight control tolerance per documentation
  no_alarms: true                # No alarms expected
  balanced_operation: true       # Both LEAD and LAG should operate efficiently
  description: "Steady-state operation achieving 95.8% accuracy within ±0.5°C"

# Validation criteria for documentation claims
validation_criteria:
  max_temperature_c: 22.5
  min_temperature_c: 21.5
  max_avg_error_c: 0.5           # Documentation standard
  max_std_dev_c: 0.3             # Documentation standard  
  min_control_accuracy_pct: 95.8 # Documentation claim
  min_cop: 2.94                  # Documentation claim
  alarm_tolerance: []            # No alarms tolerated