# Default BAS Simulation Configuration
# Professional data center cooling system parameters

system:
  name: "Data Center BAS Simulation"
  version: "1.0"
  description: "Professional Building Automation System simulation for data center cooling"

# Room/Zone Configuration
room:
  initial_temp_c: 22.0              # Initial room temperature (°C)
  ambient_temp_c: 22.0              # Ambient/outside temperature (°C)
  thermal_mass_kj_per_c: 2500.0     # Thermal mass (kJ/°C) - medium data center
  ua_kw_per_c: 0.08                 # Envelope heat transfer coefficient (kW/°C) - optimized for demos
  it_load_kw: 25.0                  # IT server load (kW) - reduced for demo stability
  infil_ua_kw_per_c: 0.0            # Infiltration heat transfer (kW/°C)
  n_virtual_sensors: 3              # Number of virtual temperature sensors

# PID Controller Configuration
pid_controller:
  kp: 15.0                          # Proportional gain (%/°C) - increased for better response
  ki: 0.5                           # Integral gain (%/(°C·s)) - increased for steady-state
  kd: 0.1                           # Derivative gain (%/(°C/s)) - light
  output_min: 0.0                   # Minimum output (%)
  output_max: 100.0                 # Maximum output (%)
  rate_limit: 50.0                  # Maximum change rate (%/s) - increased for demos
  integral_windup_limit: 80.0       # Integral windup protection (%) - increased

# CRAC Unit Configuration
# Note: Roles assigned automatically by sequencer (1st=LEAD, 2nd=LAG, 3rd+=STANDBY)
crac_units:
  - unit_id: "CRAC-01"              # Will be assigned LEAD role
    q_rated_kw: 50.0                # Rated cooling capacity (kW)
    efficiency_cop: 3.5             # Coefficient of performance
    rated_airflow_cfm: 8000.0       # Rated airflow (CFM)
    min_capacity_pct: 20.0          # Minimum capacity (%)
    max_capacity_pct: 100.0         # Maximum capacity (%)
    startup_time_s: 1.0             # Startup time (seconds) - minimal for demos
    shutdown_time_s: 1.0            # Shutdown time (seconds) - minimal for demos
    mtbf_hours: 8760.0              # Mean time between failures (hours) - 1 year
    mttr_hours: 4.0                 # Mean time to repair (hours)

  - unit_id: "CRAC-02"              # Will be assigned LAG role
    q_rated_kw: 50.0
    efficiency_cop: 3.5
    rated_airflow_cfm: 8000.0       # Rated airflow (CFM)
    min_capacity_pct: 20.0
    max_capacity_pct: 100.0
    startup_time_s: 1.0             # Startup time (seconds) - minimal for demos
    shutdown_time_s: 1.0            # Shutdown time (seconds) - minimal for demos
    mtbf_hours: 8760.0
    mttr_hours: 4.0

  - unit_id: "CRAC-03"              # Will be assigned STANDBY role
    q_rated_kw: 50.0
    efficiency_cop: 3.5
    rated_airflow_cfm: 8000.0       # Rated airflow (CFM)
    min_capacity_pct: 20.0
    max_capacity_pct: 100.0
    startup_time_s: 1.0             # Startup time (seconds) - minimal for demos
    shutdown_time_s: 1.0            # Shutdown time (seconds) - minimal for demos
    mtbf_hours: 8760.0
    mttr_hours: 4.0

# CRAC Staging Configuration
staging_config:
  temp_error_threshold: 0.8         # Temperature error for LAG staging (°C)
  staging_delay_s: 180.0            # Staging delay (seconds) - 3 minutes
  destaging_delay_s: 300.0          # Destaging delay (seconds) - 5 minutes
  rotation_runtime_hours: 24.0      # Runtime before rotation (hours) - daily
  enable_rotation: true             # Enable automatic CRAC rotation
  staging_hysteresis: 0.2           # Staging hysteresis (°C) - anti-chatter
  destaging_hysteresis: 0.3         # Destaging hysteresis (°C)

# Simulation Parameters
simulation:
  duration_minutes: 60.0            # Simulation duration (minutes)
  timestep_s: 1.0                   # Simulation timestep (seconds)
  output_interval_s: 60.0           # Data output interval (seconds)
  setpoint_c: 22.0                  # Temperature setpoint (°C)
  random_seed: 42                   # Random seed for reproducibility

# Alarm System Configuration
alarms:
  enable_alarms: true               # Enable alarm system
  high_temp_threshold_c: 27.0       # High temperature alarm (°C)
  low_temp_threshold_c: 18.0        # Low temperature alarm (°C)
  alarm_delay_s: 120.0              # Alarm activation delay (seconds)

# Telemetry and Data Collection
telemetry:
  enable_csv_export: true           # Enable CSV data export
  enable_real_time_display: true    # Enable real-time console output
  csv_output_path: "reports/"       # CSV output directory
  data_retention_hours: 24.0        # Data retention period (hours)

# Fault Simulation Configuration
# Professional fault simulation for BAS troubleshooting and diagnostics
fault_simulation:
  enable_faults: true               # Enable fault simulation system
  random_seed: 12345                # Random seed for deterministic fault injection
  
  # Sensor fault simulation
  sensor_faults:
    enable: true                    # Enable sensor fault simulation
    
    # Temperature sensor fault configurations
    temperature_sensors:
      - sensor_id: "TEMP_SENSOR_01"
        location: "Zone_1"
        enable_faults: true
        fault_types:
          - type: "drift"             # Gradual sensor drift
            probability: 0.001        # Probability per timestep
            drift_rate: 0.02          # Drift rate (°C/hour)
            max_drift: 1.0            # Maximum total drift (°C)
          - type: "bias"              # Systematic offset error
            probability: 0.0005
            bias_offset: 0.5          # Constant bias (°C)
          - type: "intermittent"      # Random dropouts
            probability: 0.0001
            dropout_duration: 30.0    # Average dropout time (seconds)
      
      - sensor_id: "TEMP_SENSOR_02"
        location: "Zone_2"
        enable_faults: true
        fault_types:
          - type: "noise"             # Electronic noise
            probability: 0.0002
            noise_amplitude: 0.1      # RMS noise amplitude (°C)
          - type: "stuck"             # Sensor frozen
            probability: 0.0001
            stuck_value: null         # null = stick at current value
  
  # Actuator fault simulation
  actuator_faults:
    enable: true                    # Enable actuator fault simulation
    
    # CRAC damper actuator configurations
    crac_dampers:
      - actuator_id: "CRAC_01_DAMPER"
        location: "CRAC-01"
        enable_faults: true
        fault_types:
          - type: "stiction"          # Static friction
            probability: 0.0005
            breakaway_threshold: 3.0  # Minimum command change (%) 
            static_friction: 1.5      # Friction resistance (%)
          - type: "backlash"          # Position hysteresis
            probability: 0.0003
            deadband: 2.0             # Deadband percentage
            hysteresis_factor: 0.3    # Hysteresis strength
          - type: "degradation"       # Performance degradation
            probability: 0.0002
            response_degradation: 0.3 # Response reduction factor
            accuracy_loss: 2.0        # Position accuracy loss (%)
      
      - actuator_id: "CRAC_02_DAMPER"
        location: "CRAC-02"
        enable_faults: true
        fault_types:
          - type: "oscillation"       # Hunting behavior
            probability: 0.0001
            amplitude: 5.0            # Oscillation amplitude (%)
            frequency: 0.1            # Oscillation frequency (Hz)
          - type: "partial_failure"   # Limited range
            probability: 0.0001
            failure_rate: 0.1         # Range reduction rate (%/hour)
  
  # Control system fault simulation
  control_faults:
    enable: true                    # Enable control system fault simulation
    
    pid_controller:
      enable_faults: true
      fault_types:
        - type: "short_cycling"      # Rapid equipment cycling
          probability: 0.0002
          cycle_threshold: 300.0      # Normal cycle time (seconds)
          short_cycle_ratio: 0.3      # Ratio of normal cycle
        - type: "controller_saturation" # Extended saturation
          probability: 0.0001
          saturation_threshold: 95.0  # Saturation threshold (%)
          saturation_duration: 120.0  # Minimum saturation time (s)
        - type: "communication_dropout" # Network failures
          probability: 0.0001
          dropout_duration: 60.0      # Average dropout time (seconds)
          max_dropout: 300.0          # Maximum dropout time (seconds)
        - type: "loop_instability"    # Control instability
          probability: 0.00005
          instability_gain: 1.5       # Gain increase factor
          oscillation_period: 600.0   # Oscillation period (seconds)
  
  # Equipment fault simulation (extends existing MTBF/MTTR)
  equipment_faults:
    enable: true                    # Enable additional equipment faults
    
    crac_units:
      - unit_id: "CRAC-01"
        additional_faults:
          - type: "performance_degradation" # Gradual capacity loss
            probability: 0.00001
            degradation_rate: 0.1     # Capacity loss rate (%/hour)
            max_degradation: 25.0     # Maximum capacity loss (%)
          - type: "efficiency_loss"   # COP degradation
            probability: 0.00001
            efficiency_loss_rate: 0.05 # COP loss rate per hour
      
      - unit_id: "CRAC-02"
        additional_faults:
          - type: "refrigerant_leak"  # Refrigerant loss
            probability: 0.000005
            leak_rate: 1.0            # Capacity loss rate (%/hour)
          - type: "compressor_wear"   # Compressor degradation
            probability: 0.000002
            wear_factor: 1.2          # Performance reduction factor

# Diagnostic System Configuration
# Professional fault detection and root cause analysis
diagnostics:
  enable: true                      # Enable diagnostic system
  
  # Diagnostic engine settings
  engine:
    evaluation_interval_s: 60.0     # How often to run diagnostics (seconds)
    confidence_threshold: 0.7       # Minimum confidence for fault confirmation
    data_buffer_size: 1000          # Maximum data points to store
    
    # Diagnostic rules configuration
    rules:
      sensor_drift_detection:
        enable: true
        evaluation_interval_s: 300.0 # 5 minutes
        confirmation_time_s: 1800.0  # 30 minutes
        drift_threshold: 1.5          # Temperature drift threshold (°C)
      
      equipment_performance:
        enable: true
        evaluation_interval_s: 600.0 # 10 minutes
        confirmation_time_s: 3600.0  # 1 hour
        performance_threshold: 0.85   # 85% of expected performance
      
      control_instability:
        enable: true
        evaluation_interval_s: 120.0 # 2 minutes
        confirmation_time_s: 600.0   # 10 minutes
        variability_threshold: 15.0   # Control signal variability (%)
      
      energy_efficiency:
        enable: true
        evaluation_interval_s: 900.0 # 15 minutes
        confirmation_time_s: 3600.0  # 1 hour
        efficiency_threshold: 0.8     # 80% of expected efficiency
  
  # Root cause analysis settings
  root_cause:
    enable: true                    # Enable root cause analysis
    analysis_depth: "detailed"      # "summary", "standard", "detailed"
    correlation_threshold: 0.6      # Minimum correlation for cause linkage
    evidence_weight: 1.0            # Weight of supporting evidence
  
  # Reporting configuration
  reporting:
    enable: true                    # Enable diagnostic reporting
    auto_generate: true             # Automatically generate reports
    
    # Report settings
    default_format: "markdown"      # "json", "csv", "markdown", "html"
    output_directory: "reports/diagnostics/"
    include_charts: true            # Include performance charts
    include_raw_data: false         # Include raw diagnostic data
    
    # Report scheduling
    daily_summary: true             # Generate daily health summary
    weekly_analysis: true           # Generate weekly trend analysis
    fault_reports: true             # Generate immediate fault reports
    
    # Report content
    audience: "technical"            # "executive", "technical", "maintenance"
    detail_level: "standard"        # "summary", "standard", "detailed"
    company_name: "Data Center Operations"
    facility_name: "Primary Data Center"

# BACnet/IP Configuration
# Professional building automation protocol integration
bacnet:
  enabled: false                    # BACnet/IP interface disabled by default
  device:
    objectName: "DC-BAS-Sim"         # BACnet device name (must be unique on network)
    objectIdentifier: 599            # Device instance number (1-4194303)
    vendorIdentifier: 15             # Vendor ID (15 = Other/Open Source)
    maxApduLengthAccepted: 1024      # Maximum APDU length (bytes)
    segmentationSupported: "segmented-both"  # Full segmentation support
    modelName: "DC-BAS-Simulation"   # Device model identifier
    firmwareRevision: "1.0.0"        # Firmware version string
    applicationSoftwareVersion: "1.0.0"  # Application version
  network:
    bind: "0.0.0.0"                 # Bind to all network interfaces
    port: 47808                      # Standard BACnet/IP UDP port
    # bbmdAddress: "192.168.1.100"   # BBMD IP (uncomment if using BBMD)
    # bbmdPort: 47808                # BBMD port
    foreignDeviceTtl: 300            # Foreign device registration TTL (seconds)
  points:
    # Analog Inputs (AI) - Read-only sensor values
    zone_temp_ai: 1                  # Zone temperature sensor (°C)
    crac1_cooling_ai: 5              # CRAC-01 cooling output (kW)
    crac2_cooling_ai: 8              # CRAC-02 cooling output (kW)
    crac3_cooling_ai: 11             # CRAC-03 cooling output (kW)
    it_load_ai: 13                   # IT equipment load (kW)
    
    # Analog Values (AV) - Read/write setpoints
    zone_temp_setpoint_av: 2         # Temperature setpoint (°C)
    
    # Analog Outputs (AO) - Control commands
    crac1_cmd_ao: 3                  # CRAC-01 capacity command (%)
    crac2_cmd_ao: 6                  # CRAC-02 capacity command (%)
    crac3_cmd_ao: 9                  # CRAC-03 capacity command (%)
    
    # Binary Inputs (BI) - Status feedback
    crac1_status_bi: 4               # CRAC-01 running status
    crac2_status_bi: 7               # CRAC-02 running status
    crac3_status_bi: 10              # CRAC-03 running status
    
    # Binary Outputs (BO) - Alarm/status outputs
    system_alarm_bo: 12              # System alarm status
    
    # Diagnostic status points
    diagnostic_status_bo: 14         # Overall diagnostic system status
    fault_count_ao: 15               # Active fault count
    health_score_ao: 16              # System health score (0-100)